# Site settings
title: NASA/ADS news, blogs, and help pages
email: adshelp@cfa.harvard.edu
description: All your questions will be answered here.
twitter_username: adsabs
github_username:  adsabs
permalink: /:categories/:title
# Build settings
markdown: kramdown

sass:
    style: :compressed
    sass_dir: _sass
