# Site settings
title: ADS news, blogs, and help pages
url: https://ui.adsabs.harvard.edu
email: adshelp@cfa.harvard.edu
description: All your questions will be answered here.

# Social
twitter:
  username: adsabs
github:
  username: adsabs
logo: /help/common/images/transparent_logo.svg

permalink: /:categories/:title
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-seo-tag
  - jekyll-last-modified-at

last-modified-at:
  date-format: '%Y-%m-%dT%H:%M:%S%:z'

defaults:
  - scope:
      path: ''
    values:
      image: /help/common/images/transparent_logo.svg
