# Site settings
title: ADS news, blogs, and help pages
url: https://ui.adsabs.harvard.edu
email: adshelp@cfa.harvard.edu
description: All your questions will be answered here.
twitter_username: adsabs
github_username: adsabs
permalink: /:categories/:title
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM

sass:
  style: :compressed
  sass_dir: _sass
